
server:
  port: 8091
spring:
  datasource:
      driver-class-name: org.h2.Driver
      # h2 内存数据库 内存模式连接配置 库名: mybatis
#      url: jdbc:h2:tcp://localhost:9092/mem:test_db
#      url: jdbc:h2:mem:test_db;DB_CLOSE_ON_EXIT=FALSE
#      url: jdbc:h2:mem:test_db
      url: jdbc:h2:/D:/coding_unit/db/test_db
#      url: jdbc:h2:file:D:\test_db;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
#       初始化数据表 DDL
      schema: classpath:sql/test_db.sql
      initialization-mode: always
  h2:
      console:
        enabled: true
        settings:
          trace: true
          web-allow-others: true
        path: /h2-console
  logging:
    level:
      cn:
        felord: debug
        #配置自动建表：updata:没有表新建，有表更新操作,控制台显示建表语句
  jpa:
    hibernate:
          ddl-auto: update
    show-sql: true
  #配置Mybatis
mybatis:
  type-aliases-package: com.perf.qi.demo.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启驼峰命名转换，如：Table(create_time) -> Entity(createTime)。不需要我们关心怎么进行字段匹配，mybatis会自动识别`大写字母与下划线`
    map-underscore-to-camel-case: true